name = "kairos-ai"
account_id = "dd6d8ca528b96621b18f498c58ffadc5"
main = "worker.mjs"
compatibility_date = "2026-08-03"
workers_dev = true
preview_urls = false

[placement]
region = "aws:us-east-1"

[vars]
OPENAI_MODEL = "gpt-5.4-nano"

[[kv_namespaces]]
binding = "QUOTA"
id = "456f850e3a2c44a7b852f8b0828dd9bc"

[[d1_databases]]
binding = "DB"
database_name = "kairos-installations"
database_id = "fce034a1-dd6f-4651-b0b7-4c778c213622"
